import type { AliasName, HarnessId, Session, SessionId } from "@launchkit/types"
import {
  type Clock,
  type IdGen,
  type Result,
  err,
  isErr,
  ok,
} from "@launchkit/utils"
import type { Database, SessionError } from "./db"

/** Fields the caller supplies; `id` and `startedAt` are generated by the store. */
export type SessionInput = {
  readonly harnessId: HarnessId
  readonly alias: AliasName
  readonly name?: string
  readonly cwd?: string
}

/**
 * Optional, all-`AND` filter for `query`. `since` is an inclusive `startedAt >=` bound;
 * `running` selects open (`true`) or closed (`false`) sessions; `limit`/`offset` paginate
 * the `startedAt DESC` result.
 */
export type SessionFilter = {
  readonly harnessId?: HarnessId
  readonly alias?: AliasName
  readonly since?: string
  readonly running?: boolean
  readonly limit?: number
  readonly offset?: number
}

export interface SessionStore {
  init(): Result<void, SessionError>
  create(input: SessionInput): Result<Session, SessionError>
  close(id: SessionId, exitCode: number): Result<Session, SessionError>
  query(filter?: SessionFilter): Result<readonly Session[], SessionError>
}

const CREATE_TABLE = `CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  harnessId TEXT NOT NULL,
  alias TEXT NOT NULL,
  startedAt TEXT NOT NULL,
  endedAt TEXT,
  exitCode INTEGER
)`

const CREATE_INDEX_STARTED =
  "CREATE INDEX IF NOT EXISTS idx_sessions_startedAt ON sessions (startedAt)"
const CREATE_INDEX_HARNESS =
  "CREATE INDEX IF NOT EXISTS idx_sessions_harnessId ON sessions (harnessId)"
const PRAGMA_COLUMNS = "PRAGMA table_info(sessions)"
const ADD_COLUMN_NAME = "ALTER TABLE sessions ADD COLUMN name TEXT"
const ADD_COLUMN_CWD = "ALTER TABLE sessions ADD COLUMN cwd TEXT"
const INSERT_SESSION =
  "INSERT INTO sessions (id, harnessId, alias, startedAt, name, cwd) VALUES (?, ?, ?, ?, ?, ?)"
const UPDATE_CLOSE =
  "UPDATE sessions SET endedAt = ?, exitCode = ? WHERE id = ?"
const SELECT_COLUMNS =
  "SELECT id, harnessId, alias, startedAt, endedAt, exitCode, name, cwd FROM sessions"
const SELECT_BY_ID = `${SELECT_COLUMNS} WHERE id = ?`

/** Map a raw sqlite row into a Session, dropping NULL endedAt/exitCode/name/cwd. */
const toSession = (row: Record<string, unknown>): Session => {
  const base: Session = {
    id: row.id as SessionId,
    harnessId: row.harnessId as HarnessId,
    alias: row.alias as AliasName,
    startedAt: String(row.startedAt),
  }
  const endedAt = row.endedAt
  const exitCode = row.exitCode
  const name = row.name
  const cwd = row.cwd
  return {
    ...base,
    ...(typeof endedAt === "string" ? { endedAt } : {}),
    ...(typeof exitCode === "number" ? { exitCode } : {}),
    ...(typeof name === "string" ? { name } : {}),
    ...(typeof cwd === "string" ? { cwd } : {}),
  }
}

/** Build a parameterized WHERE from a filter: column names go in the sql, values go in params. */
const buildWhere = (
  filter: SessionFilter,
): { readonly clause: string; readonly params: readonly unknown[] } => {
  const conditions: string[] = []
  const params: unknown[] = []
  if (filter.harnessId !== undefined) {
    conditions.push("harnessId = ?")
    params.push(filter.harnessId)
  }
  if (filter.alias !== undefined) {
    conditions.push("alias = ?")
    params.push(filter.alias)
  }
  if (filter.since !== undefined) {
    conditions.push("startedAt >= ?")
    params.push(filter.since)
  }
  if (filter.running === true) {
    conditions.push("endedAt IS NULL")
  } else if (filter.running === false) {
    conditions.push("endedAt IS NOT NULL")
  }
  const clause =
    conditions.length > 0 ? ` WHERE ${conditions.join(" AND ")}` : ""
  return { clause, params }
}

export const createSessionStore = (deps: {
  readonly db: Database
  readonly clock: Clock
  readonly idGen: IdGen
}): SessionStore => {
  const { db } = deps

  const init = (): Result<void, SessionError> => {
    const table = db.exec(CREATE_TABLE)
    if (isErr(table)) return table
    const started = db.exec(CREATE_INDEX_STARTED)
    if (isErr(started)) return started
    const harness = db.exec(CREATE_INDEX_HARNESS)
    if (isErr(harness)) return harness

    const info = db.all(PRAGMA_COLUMNS, [])
    if (isErr(info)) return info
    const existing = new Set(info.value.map((row) => String(row.name)))

    if (!existing.has("name")) {
      const added = db.exec(ADD_COLUMN_NAME)
      if (isErr(added)) return added
    }
    if (!existing.has("cwd")) {
      const added = db.exec(ADD_COLUMN_CWD)
      if (isErr(added)) return added
    }
    return ok(undefined)
  }

  return {
    init,
    create: (input: SessionInput): Result<Session, SessionError> => {
      const id = deps.idGen.next("s") as SessionId
      const startedAt = deps.clock.now().toISOString()
      const written = db.run(INSERT_SESSION, [
        id,
        input.harnessId,
        input.alias,
        startedAt,
        input.name ?? null,
        input.cwd ?? null,
      ])
      if (isErr(written)) return written
      return ok({
        id,
        harnessId: input.harnessId,
        alias: input.alias,
        startedAt,
        ...(input.name !== undefined ? { name: input.name } : {}),
        ...(input.cwd !== undefined ? { cwd: input.cwd } : {}),
      })
    },
    close: (id: SessionId, exitCode: number): Result<Session, SessionError> => {
      const endedAt = deps.clock.now().toISOString()
      const written = db.run(UPDATE_CLOSE, [endedAt, exitCode, id])
      if (isErr(written)) return written
      const fetched = db.get(SELECT_BY_ID, [id])
      if (isErr(fetched)) return fetched
      if (fetched.value === undefined) return err({ kind: "not-found" })
      return ok(toSession(fetched.value))
    },
    query: (
      filter?: SessionFilter,
    ): Result<readonly Session[], SessionError> => {
      const active = filter ?? {}
      const { clause, params: whereParams } = buildWhere(active)
      const params: unknown[] = [...whereParams]
      let sql = `${SELECT_COLUMNS}${clause} ORDER BY startedAt DESC`
      if (active.limit !== undefined) {
        sql += " LIMIT ?"
        params.push(active.limit)
      }
      if (active.offset !== undefined) {
        sql += " OFFSET ?"
        params.push(active.offset)
      }
      const rows = db.all(sql, params)
      if (isErr(rows)) return rows
      return ok(rows.value.map(toSession))
    },
  }
}
