import type { AliasName, HarnessId, Session, SessionId } from "@launchkit/types"
import {
  type Clock,
  type IdGen,
  type Result,
  isErr,
  ok,
} from "@launchkit/utils"
import type { Database, SessionError } from "./db"

/** Fields the caller supplies; `id` and `startedAt` are generated by the store. */
export type SessionInput = {
  readonly harnessId: HarnessId
  readonly alias: AliasName
}

/** Optional, all-`AND` filter for `query`. `since` is an inclusive `startedAt >=` bound. */
export type SessionFilter = {
  readonly harnessId?: HarnessId
  readonly alias?: AliasName
  readonly since?: string
}

export interface SessionStore {
  init(): Result<void, SessionError>
  create(input: SessionInput): Result<Session, SessionError>
  close(id: SessionId, exitCode: number): Result<Session, SessionError>
  query(filter?: SessionFilter): Result<readonly Session[], SessionError>
}

const CREATE_TABLE = `CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  harnessId TEXT NOT NULL,
  alias TEXT NOT NULL,
  startedAt TEXT NOT NULL,
  endedAt TEXT,
  exitCode INTEGER
)`

const CREATE_INDEX_STARTED =
  "CREATE INDEX IF NOT EXISTS idx_sessions_startedAt ON sessions (startedAt)"
const CREATE_INDEX_HARNESS =
  "CREATE INDEX IF NOT EXISTS idx_sessions_harnessId ON sessions (harnessId)"

export const createSessionStore = (deps: {
  readonly db: Database
  readonly clock: Clock
  readonly idGen: IdGen
}): SessionStore => {
  const { db } = deps

  const init = (): Result<void, SessionError> => {
    const table = db.exec(CREATE_TABLE)
    if (isErr(table)) return table
    const started = db.exec(CREATE_INDEX_STARTED)
    if (isErr(started)) return started
    const harness = db.exec(CREATE_INDEX_HARNESS)
    if (isErr(harness)) return harness
    return ok(undefined)
  }

  return {
    init,
    create: () => {
      throw new Error("not implemented until sessions-03")
    },
    close: () => {
      throw new Error("not implemented until sessions-04")
    },
    query: () => {
      throw new Error("not implemented until sessions-05")
    },
  }
}
